// GET https://wayfarer.nianticlabs.com/api/v1/vault/manage

return {
	"result": [{
		"id": "VVAGBwFUUwACU1YHBFsBBQBWAVRTDlFZA1MFVlVUA1dLBwcH",
		"title": "Den gamle skogen",
		"description": "Skilt i natursti-serie satt opp av Jevnaker almenning for å bevisstgjøre folk om skogens mange bruksområder, her om hvordan den eldre delen av skogen er blitt formet over årene",
		"lat": 60.216629,
		"lng": 10.507908,
		"city": "",
		"state": "Viken",
		"day": "2020-06-26",
		"order": 209,
		"imageUrl": "https://lh3.googleusercontent.com/G9q19NNlh6sR-AEqWKJFLL0AA52L51uvxiMs9EZIRpld6VssL27wfYUYl0KYBisMbgcElg9eYy51fdpeDj1AQBpr6A",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "DUPLICATE"
	}, {
		"id": "AVVSDldVAQZRXFECBAxUBwAAAVEAAQNZBAcAVwJRW1BLBwcH",
		"title": "Milorg slipp-plass \"Anemone\"",
		"description": "Krigsminnesmerke ved Knuvlebeitmyra for fallskjermslipp til hjemmestyrker (Milorg) fra Eidsvoll og Hurdal under 2. Verdenskrig, 24.2.1945. Særmelding (kode) på radio var \"politikeren spiller poker\"",
		"lat": 60.433036,
		"lng": 11.124565,
		"city": "",
		"state": "Viken",
		"day": "2020-08-09",
		"order": 239,
		"imageUrl": "https://lh3.googleusercontent.com/UjQTzJT8fQk_9gQp2GCDSnHHHcxrsO-bJq7kHh8ZgLIn7vi-pPiQiFHJPmI-CSTCBznhea2TR3bfttX1U80ZXb4JozA",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "WITHDRAWN"
	}, {
		"id": "VFMCVwJRBFFQUlcCBFpVUwALUwJXCVYFAVYHUgcAUlRLBwcH",
		"title": "Svarten (387moh)",
		"description": "Informasjonsskilt om Svarten og regulering av vannstanden",
		"lat": 60.096698,
		"lng": 10.55058,
		"city": "",
		"state": "Viken",
		"day": "2021-06-12",
		"order": 285,
		"imageUrl": "https://lh3.googleusercontent.com/mM7vtb7IQvdCorAeWt-gvtHG-GM5TBX-p0ZBKXdrJSzo-UKxEAlJcEVHXSIu4PTakSDOkdx9X_cbszB4iLcaaqoXVHIeicQ1WDG9oVkUGg",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "REJECTED"
	}, {
		"id": "B1JWAFUDD1MEUlddBFlVBVpQVlYEWVFWUQYGWgwJAQBLBwcH",
		"title": "Demningen ved Damtjern",
		"description": "Stor demning ved Damtjern, som forsyner Åsa kraftverk lenger ned med vann",
		"lat": 60.125848,
		"lng": 10.406418,
		"city": "",
		"state": "Viken",
		"day": "2021-08-03",
		"order": 293,
		"imageUrl": "https://lh3.googleusercontent.com/vg8piPRRrklKsSkcThMoKvDhtW0jE4hTS47p5jtgumUWO8jU7m7I4XRAJwqTolmm-2vhrvyrJ9Hptr2UiyaU4dYxUTh4gviQwdhLUuk",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "ACCEPTED"
	}, {
		"id": "XQYCDwFQBlEEUQAABFoCUQFXBARXXQRTVFENUQwEW1JLBwcH",
		"title": "Svarten",
		"description": "Informasjonsskilt over vannregulering i Svarten, 358moh",
		"lat": 60.096685,
		"lng": 10.550568,
		"city": "",
		"state": "Viken",
		"day": "2021-08-03",
		"order": 294,
		"imageUrl": "https://lh3.googleusercontent.com/ymNqAX_MIGpVxt1elS-Sa3kbq-TuxnT7JsejB6lEe09A5D6JFloLfpUiS8Fsn2g8s4rSrG1404tb8fl5M-4N_6rvgYCWWXG24-ty2y09",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "VOTING"
	}, {
		"id": "AFQCAwFRBFUCVQFUBAAGCFlXBQQHWVVRDwRQB1JSUVxLBwcH",
		"title": "Mosquito-leiren (Milorg D111.1)",
		"description": "8. Mai 1945 under 2. Verdenskrig mobiliserte Milorg avd 111.1 en leir på dette platået, for å avvæpne tyskerene i Ski.",
		"lat": 59.77386,
		"lng": 10.890601,
		"city": "",
		"state": "Viken",
		"day": "2021-08-05",
		"order": 296,
		"imageUrl": "https://lh3.googleusercontent.com/ZYIR6UeJs8q6KCyxOe0tCq3RSUeza9mpmiw1gtKD_bOWUpcMhiPF770Ho2AHPVAFcIPaCB1Mzl30dsowSJN_wYrAfs6txHWkNQSJX1jg",
		"nextUpgrade": false,
		"upgraded": false,
		"status": "NOMINATED"
	}],
	"message": null,
	"code": "OK",
	"errorsWithIcon": null,
	"fieldErrors": null,
	"errorDetails": null,
	"version": "4.0.65",
	"captcha": false
}
